baseURL = 'https://jph.im/'
languageCode = 'en-GB'
title = 'Imperative Thought'
theme = 'impthink2021'
enableEmoji = true
enableGitInfo = true
enableRobotsTxt = true

[markup.highlight]
  lineNos = true
  noClasses = false
  style = 'doom-one'

[params.github]
  username = 'jiphex'
  [params.github.siteRepo]
    owner = 'jiphex'
    repo = 'website'

[params.twitter]
  username = 'jiphex'

[params.email]
  address = 'website@james.jph.im' # Masked email

[params.license]
  url = "https://creativecommons.org/licenses/by-sa/2.0/"
  text = "CC-BY-SA"

[params]
abstract = '''
  A blog about systems administration
'''

[imaging.exif]
  # Hugo extracts the "photo taken" date/time into .Date by default.
  # Set this to true to turn it off.
  # disableDate = true

  # Hugo extracts the "photo taken where" (GPS latitude and longitude) into
  # .Long and .Lat. Set this to true to turn it off.
  disableLatLong = true

[outputs]
  home = ['HTML', 'JSON']
